#!/bin/sh

PYV=`python -c "import sys;t='{v[0]}'.format(v=list(sys.version_info));sys.stdout.write(t)";`
if [ $PYV -ne 3 ]; then
  PYTHON=python3
else
  PYTHON=python
fi

$PYTHON ../src/main.py src/freya.fr
mkdir -p build
rm -rf build/*
mv src/*.cpp build
mv src/*.h build
mv src/freya build/freya
./build/freya

if [ "$1" = "--clean" ]; then
  rm -rf src/*.cpp src/*.h build/
fi
